### ISSUE TITLE
Use golang.org/x/mod/zip?

### ISSUE THREAD

**Issue by arschles** [plexsystems/pacmod#4]
This issue stems out of discussion at https://github.com/gomods/athens/pull/1583#issuecomment-604556521. The TL;DR is that [`golang.org/x/mod/zip`](https://pkg.go.dev/golang.org/x/mod@v0.2.0/zip?tab=doc) generates proper directory structure inside the zip file, whereas https://github.com/plexsystems/pacmod/blob/master/pack/pack.go doesn't guarantee that.

We (Athens) currently have documentation on how to use `pacmod` to pre-fill the Athens on-disk database, but I'm going to mark it "alpha" or something similar to indicate that it might not always work.

If you're open to us making the fix in this repository, please let me know 😄

**Comment by jpreese** [comment]
Oh for sure, I'll definitely look into this and get it shored up if something is lacking. Thanks for reaching out!

**Comment by arschles** [comment]
@jpreese sounds good. If you'd like, I can submit a PR for this. Just let me know

**Comment by jpreese** [comment]
That would actually be huge! If you're unable to get to it as well, my goal was, now that you've reminded me 😆, to get something out by this weekend.

**Comment by jpreese** [comment]
@arschles I have released `v0.4.0` which uses `mod/zip`. At your convenience, can you see if this resolves the issue that Athens was seeing?

**Comment by jpreese** [comment]
Athens documentation has been merged into master upstream, marking as closed!
