### ISSUE TITLE
How can I pack a monorepo with many packages?

### ISSUE THREAD

**Issue by rolandjitsu** [plexsystems/pacmod#5]
I have a monorepo with a lot of packages (under `pkg`) and a single `go.mod` at the root. But when I run:
```bash
pacmod pack $VERSION ./build
```
I get:
```
2020/05/21 15:50:23 Packing module in path /Users/rolandjitsu/Work/myrepo/build...
Error: package module: create zip archive: create zip from dir: create zip /Users/rolandjitsu/Work/myrepo: module source tree too large (max size is 524288000 bytes)
Usage:
  pacmod pack <version> <outputdirectory> [flags]

Flags:
  -h, --help   help for pack
```

**Comment by jpreese** [comment]
@rolandjitsu this is a limitation that the Go team put on zip files. You can read their restrictions here: http://golang.so/src/cmd/vendor/golang.org/x/mod/zip/zip.go

The intent for this project is to be able to zip _individual_ modules. It sounds like you're looking to be able to package multiple modules given a directory. 

Right now the assumption is that your working directory is a single module that you want to pack. Though we could add the functionality you're looking for by finding each individual module and packaging them separately, outputting multiple zip files.

**Comment by rolandjitsu** [comment]
@jpreese ok, got it. I guess I could pack each module individually. Thanks for the prompt response.

**Comment by jpreese** [comment]
No problem!
